import React from "react";
import { BarChart2 } from "lucide-react";

function MetricCard({ label, value, sub, color }) {
  return (
    <div
      style={{
        background: "#F8FAFC",
        border: "1px solid var(--color-border)",
        borderRadius: 8,
        padding: "0.9rem 1rem",
        flex: "1 1 140px",
        minWidth: 120,
      }}
    >
      <div style={{ fontSize: "0.72rem", color: "var(--color-text-muted)", fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.06em" }}>
        {label}
      </div>
      <div style={{ fontSize: "1.5rem", fontWeight: 700, color: color || "var(--color-primary)", margin: "4px 0 2px" }}>
        {value}
      </div>
      {sub && (
        <div style={{ fontSize: "0.75rem", color: "var(--color-text-muted)" }}>{sub}</div>
      )}
    </div>
  );
}

export default function ResultsPanel({ evaluation, variantName, datasetName }) {
  if (!evaluation) return null;

  const {
    pearson,
    dtw,
    min_simulated,
    crosses_neutral,
    eps_min,
    eps_max,
    chart_b64,
  } = evaluation;

  const pearsonColor =
    pearson >= 0.9 ? "#16A34A" :
    pearson >= 0.75 ? "#D97706" : "#DC2626";

  const dtwColor =
    dtw <= 0.5 ? "#16A34A" :
    dtw <= 1.0 ? "#D97706" : "#DC2626";

  return (
    <div className="card">
      <div style={{ marginBottom: 16 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 3 }}>
          <BarChart2 size={16} color="var(--color-primary)" />
          <h3 style={{ color: "var(--color-primary)" }}>{variantName}</h3>
        </div>
        {datasetName && (
          <div style={{
            fontSize: "0.78rem",
            color: "var(--color-text-muted)",
            paddingLeft: 24,
            fontWeight: 500,
          }}>
            {datasetName}
          </div>
        )}
      </div>

      {/* Metric cards */}
      <div style={{ display: "flex", gap: 10, flexWrap: "wrap", marginBottom: 16 }}>
        <MetricCard
          label="Pearson Correlation"
          value={pearson >= 0 ? `+${pearson.toFixed(3)}` : pearson.toFixed(3)}
          sub="vs real follower curve"
          color={pearsonColor}
        />
        <MetricCard
          label="DTW Distance"
          value={dtw.toFixed(3)}
          sub="shape similarity (lower = better)"
          color={dtwColor}
        />
        <MetricCard
          label="Min Simulated"
          value={min_simulated >= 0 ? `+${min_simulated.toFixed(3)}` : min_simulated.toFixed(3)}
          sub={crosses_neutral ? "✓ Crosses neutral (−)" : "✗ Did not cross neutral"}
          color={crosses_neutral ? "#16A34A" : "#6B7280"}
        />
        <MetricCard
          label="ε Range"
          value={`${eps_min.toFixed(2)} – ${eps_max.toFixed(2)}`}
          sub="interaction threshold range"
        />
      </div>

      {/* Benchmark reference */}
      <div
        style={{
          background: "#EFF6FF",
          border: "1px solid #BFDBFE",
          borderRadius: 7,
          padding: "0.65rem 0.9rem",
          fontSize: "0.78rem",
          marginBottom: 16,
          lineHeight: 1.8,
        }}
      >
        <div style={{ fontWeight: 700, color: "#1D4ED8", marginBottom: 2 }}>
          Benchmark comparison
        </div>
        <div style={{ color: "#1E40AF" }}>
          MA-FDE-LLM M3b (gold): Pearson <strong>+0.944</strong>, DTW <strong>0.496</strong>
        </div>
        <div style={{ color: "#1E40AF" }}>
          FDE-LLM baseline (Yao et al.): Pearson <strong>+0.909</strong>, DTW <strong>1.854</strong>
        </div>
        <div style={{ color: "#1E40AF" }}>
          Paper benchmark range: Pearson <strong>0.88 – 0.97</strong>, DTW <strong>0.33 – 0.40</strong>
        </div>
      </div>

      {/* Chart */}
      {chart_b64 && (
        <div>
          <div style={{ fontSize: "0.8rem", fontWeight: 600, color: "var(--color-text-muted)", marginBottom: 8 }}>
            Comparison chart (generated by simulation)
          </div>
          <img
            src={`data:image/png;base64,${chart_b64}`}
            alt="Simulation comparison chart"
            style={{
              width: "100%",
              borderRadius: 8,
              border: "1px solid var(--color-border)",
            }}
          />
        </div>
      )}
    </div>
  );
}
